config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root 'main#index'
    get 'reports/report_by_category', to: 'reports#report_by_category'
    get 'reports/report_period_by_categories', to: 'reports#report_period_by_categories'
    get 'reports/report_period_by_dates', to: 'reports#report_period_by_dates'
    get 'reports/create_report_by_dates', to: 'reports#create_report_by_dates'
    get 'reports/create_report_by_category', to: 'reports#create_report_by_category'
    resources :operations
    resources :categories
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :operations, dependent: :delete_all

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :description, presence: true

  def self.find_category_name_by_params(id)
    find(id).name if id.present?
  end
end

app/models/operation.rb
# frozen_string_literal: true

class Operation < ApplicationRecord
  AMOUNT_FIELD_MIN_NUM = 0
  PAGINATION_PAGES = 5

  belongs_to :category

  validates :amount, presence: true, numericality: { greater_than: AMOUNT_FIELD_MIN_NUM }
  paginates_per PAGINATION_PAGES

  def self.find_operation_by_category(id)
    where(category_id: id) if id.present?
  end

  def self.find_operations_by_date(date_from, date_to)
    where('odate >= :date_from AND odate <= :date_to', { date_from: date_from.to_date, date_to: date_to.to_date })
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Internationalization
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.page params[:page]
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_url(@category), notice: I18n.t('category_was_successfully_created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @category.update(category_params)
      redirect_to category_url(@category), notice: I18n.t('category_was_successfully_updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_url, notice: I18n.t('category_was_successfully_destroyed')
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def index
    @all_operations = Operation.all
    @all_categories = Category.all
    @operations = Operation.page params[:page]
    @categories = Category.page params[:page]

    respond_to do |format|
      format.html { render :index }
      format.json { render json: { operations: @operations, categories: @categories } }
    end
  end
end

app/controllers/operations_controller.rb
# frozen_string_literal: true

class OperationsController < ApplicationController
  before_action :set_operation, only: %i[show edit update destroy]

  def index
    @operations = Operation.page params[:page]
  end

  def show; end

  def new
    @operation = Operation.new
  end

  def edit; end

  def create
    @operation = Operation.new(operation_params)
    if @operation.save
      redirect_to operation_url(@operation), notice: I18n.t('operation_was_successfully_created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @operation.update(operation_params)
      redirect_to operation_url(@operation), notice: I18n.t('operation_was_successfully_updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @operation.destroy

    redirect_to operations_url, notice: I18n.t('operation_was_successfully_destroyed')
  end

  private

  def set_operation
    @operation = Operation.find(params[:id])
  end

  def operation_params
    params.require(:operation).permit(:amount, :odate, :description, :category_id)
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  def create_report_by_dates; end

  def create_report_by_category; end

  def report_by_category
    if params[:operation][:category_id].blank?
      flash[:alert] = t('.choose_category')
      redirect_to reports_create_report_by_category_path, status: :found
      return
    end

    @report = ReportService::ReportByCategoryService.new(params:).call
    create_report_data_by_category
  end

  def report_period_by_categories
    @report = ReportService::ReportPeriodByCategoriesService.new(params:).call
    create_report_data_for_period
  end

  def report_period_by_dates
    @report = ReportService::ReportPeriodByDatesService.new(params:).call
    create_report_data_for_period
  end

  private

  def create_report_data_for_period
    find_categories_names
    find_total_amounts
    find_total_sum
    find_categories_and_amount
  end

  def create_report_data_by_category
    find_dates
    find_amounts
    find_operations
    find_category_name
    create_pagination_data
  end

  def find_categories_names
    @categories_names = @report[:categories_names]
  end

  def find_total_amounts
    @total_amounts = @report[:total_amounts]
  end

  def find_total_sum
    @total_sum = @report[:total_sum]
  end

  def find_categories_and_amount
    @categories_and_total_amount = Kaminari.paginate_array(@report[:categories_and_total_amount].to_a)
      .page(params[:page]).per(5)
  end

  def find_dates
    @dates = @report[:dates]
  end

  def find_amounts
    @amounts = @report[:amounts]
  end

  def find_operations
    @operations = @report[:operations]
  end

  def find_category_name
    @category_name = @report[:category_name]
  end

  def create_pagination_data
    @operations_paginated = @operations.page params[:page]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def nav_tab(title, url, options = {})
    current_page = options.delete(:current_page) || ''

    css_class = title == current_page ? 'text-secondary' : 'text-light'

    options[:class] = if options[:class]
                        options[:class] += " #{css_class}"
                      else
                        css_class
                      end

    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/header', locals: { current_page: }
  end

  def full_title(page_title = '')
    base_title = t('shared.header.title')
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/views/categories/_category.html.haml
%div{id: "#{dom_id category}"}
  %p
    %strong
      = t('.name')
      \:
    = category.name
  %p
    %strong
      = t('.description')
      \:
    = category.description

app/views/categories/_form.html.haml
= form_with(model: category) do |form|
  - if category.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(category.errors.count, "error")
        = t('.prohibited_this_category')
        \:
      %ul
        - category.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :name, style: "display: block"
    = form.text_field :name
  %div
    = form.label :description, style: "display: block"
    = form.text_field :description
  %div
    = form.submit class: 'btn btn-primary'

app/views/categories/edit.html.haml
- provide :page_title, t('.editing_category')
- currently_at t('.editing_category')

%h1= t('.editing_category')
= render "form", category: @category
%br/
%div
  = link_to t('.show_this_category'), @category
  |
  \#{link_to t('.back_to_categories'), categories_path}

app/views/categories/index.html.haml
- provide :page_title, t('.categories')
- currently_at(current_page: t('.categories'))

%p{:style => "color: green"}= notice
%h1= t('.categories')
.add-item
  %button.btn.btn-primary.mb-2{:type => "button"}= link_to t('.new_category'), new_category_path, class: "button-reset light-text "
#categories
  - @categories.each do |category|
    = render category
    %p
      = link_to t('.show_this_category'), category
= paginate @categories

app/views/categories/new.html.haml
- provide :page_title, t('.new_category')
- currently_at t('.new_category')

%h1= t('.new_category')
= render "form", category: @category
%br/
%div
  = link_to t('shared.back_to_categories'), categories_path

app/views/categories/show.html.haml
- provide :page_title, t('.edit_category')
- currently_at t('.edit_category')

%p{:style => "color: green"}= notice
= render @category
%div
  = link_to t('.edit_category'), edit_category_path(@category)
  |
  \#{link_to t('shared.back_to_categories'), categories_path}
  
  \#{button_to t('.destroy_category'), @category, method: :delete}

app/views/layouts/application.html.haml
!!!
%html{ :lang => I18n.locale }
  %head
    %title= full_title(yield(:page_title))
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:charset => "utf-8"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", defer: true
  %body
    .container
      = render 'shared/header'
      = yield

app/views/main/index.html.haml
- provide :page_title, t('.all_operations')
- currently_at t('.all_operations')

%h1= t('.all_operations')
%hr/
- @operations.each do |operation|
  %div
    %p
      %b= "#{t('.id')}:"
      = operation.id
    %p
      %b= "#{t('.description')}:"
      = operation.description
    %p
      %b= "#{t('.amount')}:"
      = operation.amount
    %p
      %b= "#{t('.date')}:"
      = operation.odate
    %p
      %b= "#{t('.category_id')}:"
      = operation.category_id
    %p
      %b= "#{t('.category_name')}:"
      = @all_categories.find(operation.category_id).name
  %hr/
%div
  = paginate @operations

app/views/operations/_form.html.haml
= form_with(model: operation) do |form|
  - if operation.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(operation.errors.count, "error")
        = t('.prohibited_this_operation')
        \:
      %ul
        - operation.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :category_id, style: "display: block"
    = form.select("category_id", Category.pluck(:name, :id), { :prompt => 'Select' })
  %div
    = form.label :amount, style: "display: block"
    = form.text_field :amount
  %div
    = form.label :odate, style: "display: block"
    = form.datetime_field :odate
  %div
    = form.label :description, style: "display: block"
    = form.text_field :description
  %div
    = form.submit t('.submit'), class: 'btn btn-primary'

app/views/operations/_operation.html.haml
%div{:id => "#{dom_id operation}"}
  %p
    %strong
      = t('.amount')
      \:
    = operation.amount
  %p
    %strong
      = t('.odate')
      \:
    = operation.odate
  %p
    %strong
      = t('.description')
      \:
    = operation.description
  %p
    %strong
      = t('.category')
      \:
    = operation.category_id

app/views/operations/edit.html.haml
- provide :page_title, t('.editing_operation')
- currently_at t('.editing_operation')

%h1= t('.editing_operation')
= render "form", operation: @operation
%br/
%div
  = link_to t('.show_this_operation'), @operation
  |
  \#{link_to t('shared.back_to_operations'), operations_path}

app/views/operations/index.html.haml
- provide :page_title, t('.operations')
- currently_at(current_page: t('.operations'))

%p{:style => "color: green"}= notice
%h1= t('.operations')
.add-item
  %button.btn.btn-primary.mb-2{:type => "button"}= link_to t('.new_operation'), new_operation_path, class: "button-reset light-text"
= render partial: "shared/operations_list"
= paginate @operations

app/views/operations/new.html.haml
- provide :page_title, t('.new_operation')
- currently_at t('.new_operation')

%h1= t('.new_operation')
= render "form", operation: @operation
%br/
%div
  = link_to t('shared.back_to_operations'), operations_path

app/views/operations/show.html.haml
- provide :page_title, t('.edit_this_operation')
- currently_at t('.edit_this_operation')

%p{:style => "color: green"}= notice
= render @operation
%div
  = link_to t('.edit_this_operation'), edit_operation_path(@operation)
  |
  \#{link_to t('shared.back_to_operations'), operations_path}
  
  \#{button_to t('.destroy_this_operation'), @operation, method: :delete}

app/views/reports/_buttons_accept.html.haml
%button.reset-button.btn.btn.btn-info{:type => "reset"}
  = link_to t('.clear'), reset, {:style=>'', :class => "button-reset"}
= f.submit t('.generate'), formaction: path, :class => 'btn btn-primary'

app/views/reports/_chart.html.erb
<div class="container">
  <canvas id="myChart" height="500px" width="1140px" style="display: block; box-sizing: border-box; height: 500px; width: 1140px;"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    const ctx = document.getElementById('myChart');

    const data = {
        labels: <%= raw @dates %>,
        datasets:[{
            label:'Гроші/Дата',
            data: <%= @amounts %>,
            fill: false,
            borderColor: 'rgb(75, 192, 192)',
            tension: 0.1
        }]
    }

    const config = {
        type: 'line',
        data: data,
        options: {
            responsive: true
        },
        plugins: []
    }

    new Chart(ctx, config);
</script>

app/views/reports/_date_choose.html.haml
.d-flex.justify-content-between
  %label.date_choose_label{:for => "date_from"}
    = t('.date_from')
    \:
  %input#date_from{:max => "2030-12-31", :min => "2018-01-01", :name => "filter[date-from]", :type => "date", :value => "#{2.months.ago.strftime('%Y-%m-%d')}"}/
.d-flex.justify-content-between
  %label.date_choose_label{:for => "date_to"}
    = t('.date_to')
    \:
  %input#date_to{:name => "filter[date-to]", :type => "date", :value => "#{Date.today.strftime('%Y-%m-%d')}"}/

app/views/reports/_form_by_category.html.haml
= form_with url: "/reports/create_report_by_category", method: :get do |f|
  .mb-3
    = select("operation", "category_id", Category.pluck(:name, :id), |
      {:prompt => t('.category')})                                   |
  .mt-2
    = render partial: "reports/buttons_accept", locals: {f: f, path: reports_report_by_category_path, reset: reports_create_report_by_category_path}

app/views/reports/_form_by_date.haml
.col-lg-3
  = form_with url: "/reports/create_form_by_date", method: :get, class: "mt-2 d-flex flex-column justify-content-between gap-2 w-200" do |f|
    = render partial: 'reports/date_choose'
    .d-flex.d-flex.justify-content-between.gap-2
      %button.reset-button.btn.btn.btn-info{:type => "reset"}
        = link_to t('reports.buttons_accept.clear'), reports_create_report_by_dates_path, {:style=>'', :class => "button-reset"}
      = f.submit t('.by_categories'), formaction: reports_report_period_by_categories_path, :class => 'btn btn-primary'
      = f.submit t('.by_dates'), formaction: reports_report_period_by_dates_path, :class => 'btn btn-primary'

app/views/reports/_report_by_dates.html.haml
%div{:style => "text-align: center"}
  %h1
    = t('.expenses_by_date_from')
    = params["filter"]["date-from"]
    = t('.to')
    = params["filter"]["date-to"]
    = @category
.d-flex.mb-20
  .table
    %table.report-table.table.table-striped
      %thead
        - if report_type == "dates"
          %th.fw-bold
            = t('.date')
        - else
          %th.fw-bold
            = t('.category')
        %th.fw-bold
          = t('.amount')
      %tbody
        - @categories_and_total_amount.each do |name, amount|
          %tr
            %td= name
            %td= amount.round(2)
            %td
      %tfoot
        %tr
          %td.fw-bold
            = t('.total')
            \:
          %td.fw-bold= @total_sum
  = render 'shared/pie_chart'
= paginate @categories_and_total_amount

app/views/reports/create_report_by_category.html.haml
%h1= t('.generator_by_category')
- if flash[:alert]
  .alert.alert-danger
    = flash[:alert]
= render "form_by_category"

app/views/reports/create_report_by_dates.html.haml
- require 'date'
%h1= t('.generator_by_date')
= render "form_by_date"

app/views/reports/report_by_category.html.haml
%div{:style => "text-align: center"}
  %h1
    = t('.expenses_by_category')
    = @category_name
= render partial: 'shared/line_chart'
= render partial: "shared/operations_list"
= paginate @operations_paginated

app/views/reports/report_by_dates.html.erb
<div style="text-align: center">
  <h1><%= t('.expenses_by_date_from') %> <%= params["filter"]["date-from"] %> <%= t('.to') %> <%= params["filter"]["date-to"] %> <%= @category %></h1>
</div>

<div class="d-flex mb-20">
  <div class="table">
    <table class="report-table table table-striped">
      <thead>
        <tr>
          <th class="fw-bold"><%= link_to t('.category'), :sort => "category_name", params: request.query_parameters %> </th>
          <th class="fw-bold"><%= link_to t('.amount'), :sort => "total_amounts", params: request.query_parameters %> </th>
        </tr>
      </thead>
      <tbody>
      <% @categories_and_total_amount.each do |name, amount| %>
        <tr>
          <td><%= name %></td>
          <td><%= amount.round(2) %></td><td>
        </tr>
      <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td class="fw-bold"><%= t('.total') %>:</td>
          <td class="fw-bold"><%= @total_sum %></td>
        </tr>
      </tfoot>
    </table>
  </div>
  <%= render 'shared/pie_chart' %>
</div>

<%#= paginate @operations_paginated %>

app/views/reports/report_period_by_categories.html.haml
= render 'report_by_dates', report_type: "categories"

app/views/reports/report_period_by_dates.html.haml
= render 'report_by_dates', report_type: "dates"

app/views/shared/_header.html.haml
%nav.navbar.navbar-expand-lg.bg-body-tertiary.bg-tertiary.sticky-top
  .container-fluid
    %a.navbar-brand{:href => root_path}= t('.title')
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        / Categories
        %li.nav-item
          = nav_tab(t('.categories'), categories_path, class: 'nav-link', current_page: current_page)

          -# = link_to "Категорії", "/uk/categories", {:class=>"nav-link text-danger"}

          -# %a.nav-link.text-secondary{:href => categories_path}
          -#   = t('.categories')

        / Operations
        %li.nav-item
          %a.nav-link{:href => operations_path}
            = t('.operations')
        / Reports
        %li.nav-item.dropdown
          %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "/reports/index", :role => "button"}
            = t('.reports')
          %ul.dropdown-menu
            %li
              %a.dropdown-item{:href => reports_create_report_by_dates_path}= t('.by_dates')
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item{:href => reports_create_report_by_category_path}= t('.by_category')
        / Languages:
        = render partial: 'shared/translation_drop_menu'

app/views/shared/_line_chart.html.haml
.container
  %canvas#myChart{:height => "500px", :style => "display: block; box-sizing: border-box; height: 500px; width: 1140px;", :width => "1140px"}
%script{:src => "https://cdn.jsdelivr.net/npm/chart.js"}
:javascript
  const ctx = document.getElementById('myChart');

  const data = {
      labels: #{raw @dates},
      datasets:[{
          label:'#{t('.money_date')}',
          data: #{@amounts},
          fill: false,
          borderColor: 'rgb(75, 192, 192)',
          tension: 0.1
      }]
  }

  const config = {
      type: 'line',
      data: data,
      options: {
          responsive: true
      },
      plugins: []
  }

  new Chart(ctx, config);

app/views/shared/_operations_list.html.haml
#operations.mt-1
  - @operations.each do |operation|
    = render operation
    %p
      = link_to t('.show_this_operation'), operation

app/views/shared/_pie_chart.html.haml
.pie_chart
  %canvas#myChart{:style => "display: block; box-sizing: border-box; height: 500px; width: 500px;"}
%script{:src => "https://cdn.jsdelivr.net/npm/chart.js"}
:javascript
  const ctx = document.getElementById('myChart');

  const data = {
      labels: #{raw @categories_names},
      datasets: [{
          label: '#{t('.expenses_by_period')}',
          data: #{@total_amounts},
          backgroundColor: [
              'rgb(255, 99, 132)',
              'rgb(54, 162, 235)',
              'rgb(255, 205, 86)',
              'rgb(0,0,128)',
              'rgb(0,128,128)',
              'rgb(128,0,128)',
              'rgb(128,128,0)',
              'rgb(128,0,0)'
          ],
          hoverOffset: 4
      }]
  };

  const config = {
      type: 'pie',
      data: data,
      options: {
          responsive: true
      },
      plugins: []
  }

  new Chart(ctx, config);

app/views/shared/_translation_drop_menu.html.haml
%li.nav-item.dropdown
  = link_to '#', class: 'nav-link dropdown-toggle', |
    data: {"bs-toggle": 'dropdown'} do              |
    = t I18n.locale
  %ul.dropdown-menu
    - I18n.available_locales.each do |locale|
      %li
        - if I18n.locale == locale
          = tag.span t(locale), class: 'dropdown-item'
        - else
          = link_to t(locale), url_for(locale: locale), |
            class: 'dropdown-item'                      |